// Mocks generated by Mockito 5.4.6 from annotations
// in global66_test/test/features/pokedex/domain/use_cases/get_favorite_pokemons_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:global66_test/features/pokedex/domain/entities/pokemon_detail.dart'
    as _i2;
import 'package:global66_test/features/pokedex/domain/entities/pokemon_summary.dart'
    as _i5;
import 'package:global66_test/features/pokedex/domain/repositories/pokedex_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonDetail_0 extends _i1.SmartFake implements _i2.PokemonDetail {
  _FakePokemonDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokedexRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokedexRepository extends _i1.Mock implements _i3.PokedexRepository {
  MockPokedexRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<void> get onFavoritesChanged => (super.noSuchMethod(
        Invocation.getter(#onFavoritesChanged),
        returnValue: _i4.Stream<void>.empty(),
      ) as _i4.Stream<void>);

  @override
  _i4.Future<List<_i5.PokemonSummary>> getPokemons({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemons,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<List<_i5.PokemonSummary>>.value(<_i5.PokemonSummary>[]),
      ) as _i4.Future<List<_i5.PokemonSummary>>);

  @override
  _i4.Future<_i2.PokemonDetail> getPokemonDetail(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonDetail,
          [name],
        ),
        returnValue: _i4.Future<_i2.PokemonDetail>.value(_FakePokemonDetail_0(
          this,
          Invocation.method(
            #getPokemonDetail,
            [name],
          ),
        )),
      ) as _i4.Future<_i2.PokemonDetail>);

  @override
  _i4.Future<void> toggleFavorite(_i2.PokemonDetail? pokemon) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [pokemon],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isFavorite(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.PokemonDetail>> getFavoritePokemons() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoritePokemons,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.PokemonDetail>>.value(<_i2.PokemonDetail>[]),
      ) as _i4.Future<List<_i2.PokemonDetail>>);
}
