// Mocks generated by Mockito 5.4.6 from annotations
// in global66_test/test/features/pokedex/data/repositories/pokedex_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:global66_test/features/pokedex/data/models/pokemon_detail_response.dart'
    as _i3;
import 'package:global66_test/features/pokedex/data/models/pokemon_list_response.dart'
    as _i2;
import 'package:global66_test/features/pokedex/data/models/pokemon_species_response.dart'
    as _i4;
import 'package:global66_test/features/pokedex/data/models/pokemon_type_detail_response.dart'
    as _i5;
import 'package:global66_test/features/pokedex/data/sources/local/i_pokedex_local_data_source.dart'
    as _i8;
import 'package:global66_test/features/pokedex/data/sources/remote/i_pokedex_remote_data_source.dart'
    as _i6;
import 'package:global66_test/features/pokedex/domain/entities/pokemon_detail.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonListResponse_0 extends _i1.SmartFake
    implements _i2.PokemonListResponse {
  _FakePokemonListResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonDetailResponse_1 extends _i1.SmartFake
    implements _i3.PokemonDetailResponse {
  _FakePokemonDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonSpeciesResponse_2 extends _i1.SmartFake
    implements _i4.PokemonSpeciesResponse {
  _FakePokemonSpeciesResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonTypeDetailResponse_3 extends _i1.SmartFake
    implements _i5.PokemonTypeDetailResponse {
  _FakePokemonTypeDetailResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IPokedexRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPokedexRemoteDataSource extends _i1.Mock
    implements _i6.IPokedexRemoteDataSource {
  MockIPokedexRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.PokemonListResponse> getPokemons({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemons,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i7.Future<_i2.PokemonListResponse>.value(
            _FakePokemonListResponse_0(
          this,
          Invocation.method(
            #getPokemons,
            [],
            {
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i7.Future<_i2.PokemonListResponse>);

  @override
  _i7.Future<_i3.PokemonDetailResponse> getPokemonDetail(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonDetail,
          [name],
        ),
        returnValue: _i7.Future<_i3.PokemonDetailResponse>.value(
            _FakePokemonDetailResponse_1(
          this,
          Invocation.method(
            #getPokemonDetail,
            [name],
          ),
        )),
      ) as _i7.Future<_i3.PokemonDetailResponse>);

  @override
  _i7.Future<_i4.PokemonSpeciesResponse> getPokemonSpecies(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonSpecies,
          [url],
        ),
        returnValue: _i7.Future<_i4.PokemonSpeciesResponse>.value(
            _FakePokemonSpeciesResponse_2(
          this,
          Invocation.method(
            #getPokemonSpecies,
            [url],
          ),
        )),
      ) as _i7.Future<_i4.PokemonSpeciesResponse>);

  @override
  _i7.Future<_i5.PokemonTypeDetailResponse> getPokemonTypeDetail(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonTypeDetail,
          [url],
        ),
        returnValue: _i7.Future<_i5.PokemonTypeDetailResponse>.value(
            _FakePokemonTypeDetailResponse_3(
          this,
          Invocation.method(
            #getPokemonTypeDetail,
            [url],
          ),
        )),
      ) as _i7.Future<_i5.PokemonTypeDetailResponse>);
}

/// A class which mocks [IPokedexLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPokedexLocalDataSource extends _i1.Mock
    implements _i8.IPokedexLocalDataSource {
  MockIPokedexLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> saveFavoritePokemon(_i9.PokemonDetail? pokemon) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFavoritePokemon,
          [pokemon],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeFavoritePokemon(int? id) => (super.noSuchMethod(
        Invocation.method(
          #removeFavoritePokemon,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i9.PokemonDetail>> getFavoritePokemons() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoritePokemons,
          [],
        ),
        returnValue:
            _i7.Future<List<_i9.PokemonDetail>>.value(<_i9.PokemonDetail>[]),
      ) as _i7.Future<List<_i9.PokemonDetail>>);

  @override
  _i7.Future<bool> isFavorite(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [id],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}
