// Mocks generated by Mockito 5.4.6 from annotations
// in global66_test/test/features/pokedex/presentation/controllers/favorites_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:global66_test/features/pokedex/domain/entities/pokemon_detail.dart'
    as _i4;
import 'package:global66_test/features/pokedex/domain/use_cases/get_favorite_pokemons_use_case.dart'
    as _i2;
import 'package:global66_test/features/pokedex/domain/use_cases/toggle_favorite_use_case.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetFavoritePokemonsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFavoritePokemonsUseCase extends _i1.Mock
    implements _i2.GetFavoritePokemonsUseCase {
  MockGetFavoritePokemonsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PokemonDetail>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.PokemonDetail>>.value(<_i4.PokemonDetail>[]),
      ) as _i3.Future<List<_i4.PokemonDetail>>);

  @override
  _i3.Stream<List<_i4.PokemonDetail>> watch() => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.PokemonDetail>>.empty(),
      ) as _i3.Stream<List<_i4.PokemonDetail>>);
}

/// A class which mocks [ToggleFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleFavoriteUseCase extends _i1.Mock
    implements _i5.ToggleFavoriteUseCase {
  MockToggleFavoriteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(_i4.PokemonDetail? pokemon) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [pokemon],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
