// Mocks generated by Mockito 5.4.6 from annotations
// in global66_test/test/features/pokedex/presentation/controllers/pokedex_list_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:global66_test/features/pokedex/domain/entities/pokemon_detail.dart'
    as _i2;
import 'package:global66_test/features/pokedex/domain/use_cases/get_favorite_pokemons_use_case.dart'
    as _i5;
import 'package:global66_test/features/pokedex/domain/use_cases/get_pokemon_list_with_details_use_case.dart'
    as _i3;
import 'package:global66_test/features/pokedex/domain/use_cases/search_pokemon_use_case.dart'
    as _i7;
import 'package:global66_test/features/pokedex/domain/use_cases/toggle_favorite_use_case.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonDetail_0 extends _i1.SmartFake implements _i2.PokemonDetail {
  _FakePokemonDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPokemonListWithDetailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonListWithDetailsUseCase extends _i1.Mock
    implements _i3.GetPokemonListWithDetailsUseCase {
  MockGetPokemonListWithDetailsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.PokemonDetail>> call({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.PokemonDetail>>.value(<_i2.PokemonDetail>[]),
      ) as _i4.Future<List<_i2.PokemonDetail>>);
}

/// A class which mocks [GetFavoritePokemonsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFavoritePokemonsUseCase extends _i1.Mock
    implements _i5.GetFavoritePokemonsUseCase {
  MockGetFavoritePokemonsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.PokemonDetail>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.PokemonDetail>>.value(<_i2.PokemonDetail>[]),
      ) as _i4.Future<List<_i2.PokemonDetail>>);

  @override
  _i4.Stream<List<_i2.PokemonDetail>> watch() => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
        ),
        returnValue: _i4.Stream<List<_i2.PokemonDetail>>.empty(),
      ) as _i4.Stream<List<_i2.PokemonDetail>>);
}

/// A class which mocks [ToggleFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleFavoriteUseCase extends _i1.Mock
    implements _i6.ToggleFavoriteUseCase {
  MockToggleFavoriteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(_i2.PokemonDetail? pokemon) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [pokemon],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SearchPokemonUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchPokemonUseCase extends _i1.Mock
    implements _i7.SearchPokemonUseCase {
  MockSearchPokemonUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PokemonDetail> call(String? name) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [name],
        ),
        returnValue: _i4.Future<_i2.PokemonDetail>.value(_FakePokemonDetail_0(
          this,
          Invocation.method(
            #call,
            [name],
          ),
        )),
      ) as _i4.Future<_i2.PokemonDetail>);
}
